import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function ExportPDF({ stateSummary = {} }) {

  const exportPDF = () => {

    const doc = new jsPDF();

    const reportDate =
      new Date().toLocaleString();

    doc.setFontSize(20);
    doc.text(
      "Bauchi State Election Dashboard",
      14,
      20
    );

    doc.setFontSize(14);
    doc.text(
      "Official Election Report",
      14,
      30
    );

    doc.setFontSize(10);
    doc.text(
      `Generated: ${reportDate}`,
      14,
      38
    );

    autoTable(doc, {
      startY: 50,
      head: [[
        "State",
        "Winner",
        "Total Votes",
        "Valid Votes",
        "Polling Units"
      ]],
      body: [[
        stateSummary.state_name || "Bauchi",
        stateSummary.leading_party || "-",
        stateSummary.total_votes_cast || 0,
        stateSummary.total_valid_votes || 0,
        stateSummary.polling_units_reported || 0
      ]]
    });

    const parties = [

      ["AAC", stateSummary.aac || 0],
      ["ADC", stateSummary.adc || 0],
      ["ADP", stateSummary.adp || 0],
      ["APC", stateSummary.apc || 0],
      ["APGA", stateSummary.apga || 0],
      ["APM", stateSummary.apm || 0],
      ["APP", stateSummary.app || 0],
      ["BP", stateSummary.bp || 0],
      ["LP", stateSummary.lp || 0],
      ["NDC", stateSummary.ndc || 0],
      ["NNPP", stateSummary.nnpp || 0],
      ["NRM", stateSummary.nrm || 0],
      ["PDP", stateSummary.pdp || 0],
      ["PRP", stateSummary.prp || 0],
      ["SDP", stateSummary.sdp || 0],
      ["YPP", stateSummary.ypp || 0],
      ["ZLP", stateSummary.zlp || 0]

    ];

    autoTable(doc, {
      startY:
        doc.lastAutoTable.finalY + 15,

      head: [[
        "Political Party",
        "Votes"
      ]],

      body: parties
    });

    doc.setFontSize(12);

    doc.text(

      `Leading Party: ${
        stateSummary.leading_party || "-"
      }`,

      14,

      doc.lastAutoTable.finalY + 20
    );

    doc.setFontSize(9);

    doc.text(

      "Generated by Bauchi Election Dashboard",

      14,

      285
    );

    doc.save(

      `Bauchi_Election_Report_${
        new Date().getTime()
      }.pdf`
    );
  };

  return (

    <button
      onClick={exportPDF}
      style={buttonStyle}
    >
      Export PDF Report
    </button>

  );
}

const buttonStyle = {

  padding: "12px 20px",

  backgroundColor: "#1e3a8a",

  color: "#fff",

  border: "none",

  borderRadius: "6px",

  cursor: "pointer",

  fontWeight: "bold"
};

export default ExportPDF;